services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r djangoapp/requirements.txt
    startCommand: gunicorn project.wsgi:application --bind
    autoDeploy: true
